name: device_frame
description: Mockups for common devices.
version: 0.3.0
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter_svg: ^0.20.0-nullsafety.3
  path_drawing: ^0.5.0-nullsafety.0
  freezed_annotation: ^0.13.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.0.0-nullsafety.0
  freezed: ^0.13.0-nullsafety.2
  pedantic: ^1.10.0
  xml: ^5.0.0-nullsafety.1
