name: device_frame
description: Mockups for common devices.
version: 0.1.1
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1 
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.8.0
  freezed: ^0.10.4
  flutter_test:
    sdk: flutter

flutter:
