name: device_preview_example
description: A simple demonstration of device_preview.

version: 1.0.1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets:
  device_preview:
    path: ../
  cupertino_icons: ^0.1.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter 
  pedantic: 1.8.0+1

dependency_overrides:
  pedantic: 1.9.0

flutter:
  uses-material-design: true 