name: device_preview
version: 0.7.0-nullsafety.0
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0-nullsafety.3
  path_provider: ^2.0.0-nullsafety
  device_frame: ^0.4.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  http: ^0.13.0-nullsafety.0
  freezed_annotation: ">=0.13.0-nullsafety.0 <1.0.0"
  json_annotation: ">=4.0.0-nullsafety.0 <5.0.0"
  meta: ^1.3.0-nullsafety.6
  shared_preferences: ^2.0.0-nullsafety
  pedantic: ^1.10.0
  path: ^1.8.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.0-nullsafety.0
