name: device_preview
version: 0.7.2
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.12.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  path_provider: ^2.0.1
  device_frame: ^0.4.1 
  font_awesome_flutter: ^9.0.0
  http: ^0.13.0 
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.4
  pedantic: ^1.10.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.2
  analyzer: ^1.1.0
